export { default as TestMissed } from './TestMissed';
export { default as OngoingTest } from './ongoingTest';
export { default as AppNewsUpdate } from './TestCard';
export { default as UpcomingTest } from './UpcomingTest';
export { default as MutipleCheck } from '../test/MultipleCheck';
export { default as TodayTest } from './TodayTest';
export { default as SingleCheck } from '../test/SingleCheck';
export { default as ResultMutipleCheck } from '../test/ResultMultipleCheck';
export { default as ResultSingleCheck } from '../test/ResultSingleCheck';
export { default as UpcomingTestTable} from './UpcomingTestTable';
export { default as SubmittedTestTable} from './SubmittedTestTable';
