export const STUDENTLOGIN = 'STUDENTLOGIN';
export const STUDENTREGISTRATION = 'STUDENTREGISTRATION';
export const STUDENTLOGOUT = 'STUDENTLOGOUT';
export const STUDENTLOGINWITHOUTTOKEN = 'STUDENTLOGINWITHOUTTOKEN';
export const STUDENTPROFILE = 'STUDENTPROFILE';
export const STUDENTTESTDETAILS = 'STUDENTTESTDETAILS';
export const STUDENTTEST = 'STUDENTTEST';
export const STUDENTTESTANSWER = 'STUDENTTESTANSWER';
export const STUDENTRESULT = 'STUDENTRESULT';

export const TEACHERLOGIN = 'TEACHERLOGIN';
export const TEACHERREGISTRATION = 'TEACHERREGISTRATION';
export const TEACHERLOGOUT = 'TEACHERLOGOUT';
export const TEACHERLOGINWITHOUTTOKEN = 'TEACHERLOGINWITHOUTTOKEN';
export const TEACHERPROFILE = 'TEACHERPROFILE';
export const TEACHERTESTDETAILS = 'TEACHERTESTDETAILS';
export const TEACHERTEST = 'TEACHERTEST';

export const ERROR  = 'ERROR';
export const BRANCH = 'BRANCH';